name: codingingis
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip  
  - pandas>=1.1.1
  - matplotlib>=3.3.1
  - geopandas>=0.8.0
  - descartes>=1.1.0
  - pip:
    - quantecon
    - jupyter-book