title                       : Coding in GIS
author                      : Nils Ratnaweera
logo                        : zhaw_lsfm_iunr_blau.jpg
html:
  extra_navbar              : Built with ‚ù§ and <a href="https://jupyterbook.org">Jupyter Book</a>
  favicon                   : favicon.png
  
  
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : false  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : https://jupyterhub01.zhaw.ch  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : false # The URL of Google Colab (e.g., https://colab.research.google.com)
  
repository:
  url                       : https://github.com/ratnanil/codingingis/